// solid-v/src/components/ui/accordion.tsx
import type { JSX } from "solid-js";

import { IconChevronDown } from "@tabler/icons-solidjs";

export function Accordion(props: JSX.HTMLAttributes<HTMLDivElement>) {
  return <div class={`space-y-2 ${props.class || ""}`.trim()}>{props.children}</div>;
}

export function AccordionItem(props: JSX.HTMLAttributes<HTMLDetailsElement> & { open?: boolean }) {
  return (
    <details open={props.open} class={`border-b border-border ${props.class || ""}`.trim()}>
      {props.children}
    </details>
  );
}

export function AccordionTrigger(props: JSX.HTMLAttributes<HTMLElement>) {
  return (
    <summary class={`flex cursor-pointer list-none items-center justify-between py-4 text-left font-semibold transition-all hover:underline [&::-webkit-details-marker]:hidden ${props.class || ""}`.trim()}>
      <span>{props.children}</span>
      <IconChevronDown width={16} height={16} strokeWidth={2} class="ml-3 shrink-0 opacity-60 transition-transform duration-200" aria-hidden="true" />
    </summary>
  );
}

export function AccordionContent(props: JSX.HTMLAttributes<HTMLDivElement>) {
  return <div class={`overflow-hidden pb-4 pt-0 text-sm ${props.class || ""}`.trim()}>{props.children}</div>;
}

// src/components/ui/accordion.tsx
"use client";

import * as AccordionPrimitive from "@radix-ui/react-accordion";
import { IconChevronDown } from "@tabler/icons-react";
import * as React from "react";
import { cn } from "@/lib/utils";

const Accordion = AccordionPrimitive.Root;

const AccordionItem = React.forwardRef<
  React.ComponentRef<typeof AccordionPrimitive.Item>,
  React.ComponentPropsWithoutRef<typeof AccordionPrimitive.Item>
>(({ className, ...props }, ref) => (
  <AccordionPrimitive.Item
    ref={ref}
    className={cn("border-b border-border", className)}
    {...props}
  />
));
AccordionItem.displayName = "AccordionItem";

const AccordionTrigger = React.forwardRef<
  React.ComponentRef<typeof AccordionPrimitive.Trigger>,
  React.ComponentPropsWithoutRef<typeof AccordionPrimitive.Trigger>
>(({ className, children, ...props }, ref) => (
  <AccordionPrimitive.Header className="flex">
    <AccordionPrimitive.Trigger
      ref={ref}
      className={cn(
        "flex flex-1 items-center justify-between py-4 text-left font-semibold transition-all hover:underline [&[data-state=open]>svg]:rotate-180",
        className,
      )}
      {...props}
    >
      {children}
      <IconChevronDown
        width={16}
        height={16}
        strokeWidth={2}
        className="shrink-0 opacity-60 transition-transform duration-200"
        aria-hidden="true"
      />
    </AccordionPrimitive.Trigger>
  </AccordionPrimitive.Header>
));
AccordionTrigger.displayName = AccordionPrimitive.Trigger.displayName;

const AccordionContent = React.forwardRef<
  React.ElementRef<typeof AccordionPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof AccordionPrimitive.Content>
>(({ className, children, ...props }, ref) => (
  <AccordionPrimitive.Content
    ref={ref}
    className="overflow-hidden text-sm transition-all data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down"
    {...props}
  >
    <div className={cn("pb-4 pt-0", className)}>{children}</div>
  </AccordionPrimitive.Content>
));

AccordionContent.displayName = AccordionPrimitive.Content.displayName;

export { Accordion, AccordionContent, AccordionItem, AccordionTrigger };
