// solid-v/src/components/ui/etheral-shadow.tsx
import type { JSX } from "solid-js";

type NoiseConfig = {
  opacity: number;
  scale: number;
};

type ShadowOverlayProps = {
  sizing?: "fill" | "stretch";
  color?: string;
  noise?: NoiseConfig;
  className?: string;
  children: JSX.Element;
  maskImageURL?: string;
  opacity?: number;
};

export function EtheralShadow(props: ShadowOverlayProps) {
  const sizing = props.sizing ?? "fill";
  const color = props.color ?? "var(--secondary)";
  const maskImageURL = props.maskImageURL ?? "/mask-2.png";
  const opacity = props.opacity ?? 1;

  return (
    <div class={props.className} style={{ position: "relative", overflow: "hidden", width: "100%", height: "100%" }}>
      <div
        class="absolute inset-0"
        style={{
          backgroundColor: color,
          maskImage: `url('${maskImageURL}')`,
          maskSize: sizing === "stretch" ? "100% 100%" : "cover",
          maskRepeat: "no-repeat",
          maskPosition: "center",
          opacity,
        }}
      />

      <div class="relative z-10 h-full w-full">{props.children}</div>

      {props.noise && props.noise.opacity > 0 && (
        <div
          class="pointer-events-none absolute inset-0"
          style={{
            backgroundImage: 'url("/noise.png")',
            backgroundSize: `${props.noise.scale * 200}px`,
            backgroundRepeat: "repeat",
            opacity: props.noise.opacity / 2,
          }}
        />
      )}
    </div>
  );
}

// src/components/ui/etheral-shadow.tsx
import {
  type AnimationPlaybackControls,
  animate,
  useMotionValue,
} from "framer-motion";
import {
  type CSSProperties,
  type ReactNode,
  useEffect,
  useId,
  useRef,
} from "react";

interface AnimationConfig {
  preview?: boolean;
  scale: number;
  speed: number;
}

interface NoiseConfig {
  opacity: number;
  scale: number;
}

interface ShadowOverlayProps {
  type?: "preset" | "custom";
  presetIndex?: number;
  sizing?: "fill" | "stretch";
  color?: string;
  noise?: NoiseConfig;
  style?: CSSProperties;
  className?: string;
  children: ReactNode;
  maskImageURL?: string;
  opacity?: number;
}

function mapRange(
  value: number,
  fromLow: number,
  fromHigh: number,
  toLow: number,
  toHigh: number,
): number {
  if (fromLow === fromHigh) {
    return toLow;
  }
  const percentage = (value - fromLow) / (fromHigh - fromLow);
  return toLow + percentage * (toHigh - toLow);
}

const useInstanceId = (): string => {
  const id = useId();
  const cleanId = id.replace(/:/g, "");
  const instanceId = `shadowoverlay-${cleanId}`;
  return instanceId;
};

export function EtheralShadow({
  sizing = "fill",
  color = "var(--secondary)",
  noise,
  style,
  className,
  children,
  maskImageURL = "/mask-3.png",
  opacity = 1,
}: ShadowOverlayProps) {
  const animation = { scale: 100, speed: 90 } as AnimationConfig;
  const id = useInstanceId();
  const animationEnabled = animation && animation.scale > 0;
  const feColorMatrixRef = useRef<SVGFEColorMatrixElement>(null);
  const hueRotateMotionValue = useMotionValue(180);
  const hueRotateAnimation = useRef<AnimationPlaybackControls | null>(null);

  const displacementScale = animation
    ? mapRange(animation.scale, 1, 100, 20, 100)
    : 0;
  const animationDuration = animation
    ? mapRange(animation.speed, 1, 100, 1000, 50)
    : 1;

  useEffect(() => {
    if (feColorMatrixRef.current && animationEnabled) {
      if (hueRotateAnimation.current) {
        hueRotateAnimation.current.stop();
      }
      hueRotateMotionValue.set(0);
      hueRotateAnimation.current = animate(hueRotateMotionValue, 360, {
        duration: animationDuration / 25,
        repeat: Infinity,
        repeatType: "loop",
        repeatDelay: 0,
        ease: "linear",
        delay: 0,
        onUpdate: (value: number) => {
          if (feColorMatrixRef.current) {
            feColorMatrixRef.current.setAttribute("values", String(value));
          }
        },
      });

      return () => {
        if (hueRotateAnimation.current) {
          hueRotateAnimation.current.stop();
        }
      };
    }
  }, [animationEnabled, animationDuration, hueRotateMotionValue]);

  return (
    <div
      className={className}
      style={{
        overflow: "hidden",
        position: "relative",
        width: "100%",
        height: "100%",
        ...style,
      }}
    >
      <div
        style={{
          position: "absolute",
          inset: -displacementScale,
          filter: animationEnabled ? `url(#${id}) blur(4px)` : "none",
        }}
      >
        {animationEnabled && (
          // biome-ignore lint/a11y/noSvgWithoutTitle: <it just works>
          <svg style={{ position: "absolute" }}>
            <defs>
              <filter id={id}>
                <feTurbulence
                  result="undulation"
                  numOctaves="2"
                  baseFrequency={`${mapRange(animation.scale, 0, 100, 0.001, 0.0005)},${mapRange(animation.scale, 0, 100, 0.004, 0.002)}`}
                  seed="0"
                  type="turbulence"
                />
                <feColorMatrix
                  ref={feColorMatrixRef}
                  in="undulation"
                  type="hueRotate"
                  values="180"
                />
                <feColorMatrix
                  in="dist"
                  result="circulation"
                  type="matrix"
                  values="4 0 0 0 1  4 0 0 0 1  4 0 0 0 1  1 0 0 0 0"
                />
                <feDisplacementMap
                  in="SourceGraphic"
                  in2="circulation"
                  scale={displacementScale}
                  result="dist"
                />
                <feDisplacementMap
                  in="dist"
                  in2="undulation"
                  scale={displacementScale}
                  result="output"
                />
              </filter>
            </defs>
          </svg>
        )}
        <div
          style={{
            backgroundColor: color,
            maskImage: `url('${maskImageURL}')`,
            maskSize: sizing === "stretch" ? "100% 100%" : "cover",
            maskRepeat: "no-repeat",
            maskPosition: "center",
            width: "100%",
            height: "100%",
            opacity,
          }}
        />
      </div>

      <div
        style={{
          position: "relative",
          width: "100%",
          height: "100%",
          zIndex: 10,
        }}
      >
        {children}
      </div>

      {noise && noise.opacity > 0 && (
        <div
          style={{
            position: "absolute",
            inset: 0,
            backgroundImage: `url("/noise.png")`,
            backgroundSize: noise.scale * 200,
            backgroundRepeat: "repeat",
            opacity: noise.opacity / 2,
          }}
        />
      )}
    </div>
  );
}
